<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="dotnet07-PC" name="thingblu.TestsCasesManager.VerifyAddOrder" tests="1" failures="0" timestamp="22 Jun 2018 06:12:14 GMT" time="0.000" errors="1">
  <testcase name="signInWithValidCredentials" time="0.000" classname="thingblu.TestsCasesManager.VerifyAddOrder">
    <error type="org.testng.TestNGException" message="
Data Provider public java.lang.Object[][] thingblu.core.DataProviders.orderEntryData() throws jxl.read.biff.BiffException,java.lang.Exception must return either Object[][] or Iterator&lt;Object&gt;[], not class [[Ljava.lang.Object;">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] thingblu.core.DataProviders.orderEntryData() throws jxl.read.biff.BiffException,java.lang.Exception must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- signInWithValidCredentials -->
</testsuite> <!-- thingblu.TestsCasesManager.VerifyAddOrder -->
